version: '3.9'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  postgres_data:
