name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Deploy to VPS
      env:
        VPS_USER: ${{ secrets.VPS_USER }}
        VPS_HOST: ${{ secrets.VPS_HOST }}
        VPS_PATH: ${{ secrets.VPS_PATH }}
      run: |
        ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST "
          set -e
          cd $VPS_PATH
          git pull origin master
          sudo docker-compose down
          sudo docker-compose up -d --build
        "
